// <auto-generated />
using System;
using CW_14_Kolokwium.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CW_14_Kolokwium.Migrations
{
    [DbContext(typeof(KolosDbContext))]
    [Migration("20200618091018_initial6")]
    partial class initial6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CW_14_Kolokwium.Models.Championhip_Team", b =>
                {
                    b.Property<int>("idChampionship")
                        .HasColumnType("int");

                    b.Property<int>("idTeam")
                        .HasColumnType("int");

                    b.Property<float>("score")
                        .HasColumnType("real");

                    b.HasKey("idChampionship");

                    b.HasIndex("idTeam");

                    b.ToTable("championship_Teams");
                });

            modelBuilder.Entity("CW_14_Kolokwium.Models.Championship", b =>
                {
                    b.Property<int>("IdChampionShip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdChampionShip");

                    b.ToTable("championships");
                });

            modelBuilder.Entity("CW_14_Kolokwium.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPlayer");

                    b.ToTable("players");
                });

            modelBuilder.Entity("CW_14_Kolokwium.Models.Player_Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("NumofShirt")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTeam");

                    b.HasIndex("IdPlayer");

                    b.ToTable("player_Teams");
                });

            modelBuilder.Entity("CW_14_Kolokwium.Models.Team", b =>
                {
                    b.Property<int>("IdTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTeam");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CW_14_Kolokwium.Models.Championhip_Team", b =>
                {
                    b.HasOne("CW_14_Kolokwium.Models.Championship", "championship")
                        .WithMany("championhip_Teams")
                        .HasForeignKey("idChampionship")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW_14_Kolokwium.Models.Team", "team")
                        .WithMany("championhip_Teams")
                        .HasForeignKey("idTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CW_14_Kolokwium.Models.Player_Team", b =>
                {
                    b.HasOne("CW_14_Kolokwium.Models.Player", "player")
                        .WithMany("player_Teams")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CW_14_Kolokwium.Models.Team", "team")
                        .WithMany("player_Teams")
                        .HasForeignKey("IdTeam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
